### ISSUE TITLE
News aggregator for the Elm community

### ISSUE THREAD

**Issue by lukewestby** [elm-lang/projects#12]
Hi all!

First I want to say how much I'm loving Elm and how welcoming and helpful the community has been so far. Thanks to all of you!

I'd like to suggest the creation of a community-driven news aggregator for Elm. (If this already exists, feel free to close this!) Virtually everything I find out in JavaScript-land comes from echojs.com and javascript.com/news. Community-driven lists like these really help to organize neat new packages and ideas for the language. The ability to vote or curate also helps to filter the most interesting and well-designed contributions as the language continues to scale in popularity.

I like structure of echojs.com because of the HN-like simplicity of layout and voting functionality, and I like javascript.com/news because the posts are curated before going live. Perhaps some combination of these systems could work for Elm?

Let me know what you all think!

**Comment by jvoigtlaender** [comment]
There is this: http://planet.elm-lang.org/.

Does it go in the direction of what you are looking for?

I think you can influence what direction it is taking by contributing at https://github.com/Gizra/planet-elm.

**Comment by lukewestby** [comment]
"Having this main site as a central place for aggregating all the interesting content about Elm is yet another step in getting Elm into the mainstream."

This is exactly what I was looking for. Thanks!
