### ISSUE TITLE
Add emmet support for elm?

### ISSUE THREAD

**Issue by Horusiath** [elm-lang/projects#13]
Hi. I've come here with a question/idea. Do you have any support for Zen Coding/[Emmet](https://en.wikipedia.org/wiki/Emmet_%28software%29)-based HTML boilerplate generation for Elm language in plans?

It could make easier to generate DOM elements - which are often required in great number in real life applications - using well-known concepts.

**Comment by jeremy-w** [comment]
Right now, you can probably get pretty far with regular Emmet + [html-to-elm](https://atom.io/packages/html-to-elm).

**Comment by evancz** [comment]
I don't think it makes sense to add this to the list. I think the root concerns here will be addressed in a different way ultimately.

**Comment by maximalism2** [comment]
@Horusiath  @jeremy-w if you are still looking for something to use emmet with elm here is an extension for VSCode which does it:
https://marketplace.visualstudio.com/items?itemName=necinc.elmmet
