### ISSUE TITLE
Allow for per-user cache of downloaded packages to save network usage and disk space

### ISSUE THREAD

**Issue by davidascher** [elm-lang/projects#14]
I'm often working on new projects in low-connectivity environments, and it ends up frustrating that package installation is stalled while I know I have multiple  copies of these packages already installed.

Given the strong versioning, it seems like a developer mode at least of `elm-package` could cache the packages in a per-user `elm-stuff` (maybe under `~/.elm/elm-stuff`), rather than create one per project directory.

Note: i have the same issue w/ `npm`, I don't understand why that community hasn't done something like this either, there may be very good reasons I just don't know.

**Comment by iqualfragile** [comment]
yes, please

**Comment by evancz** [comment]
This kind of thing is planned for some upcoming work I'm doing!
