### ISSUE TITLE
Any interest in comparing Elm's virtual-dom to Snabbdom & Inferno?

### ISSUE THREAD

**Issue by joshburgess** [elm-lang/projects#15]
Would you be interested in comparing to more high performance JS virtual DOM implementations like Snabbdom & Inferno alongside React & the others listed? I think it would be cool to see.

**Comment by evancz** [comment]
That project is just wrapping up. I think it could be cool, but I don't need it for the blog post I am writing. So I'd say go for it if you are curious!
