### ISSUE TITLE
In browser elm repl

### ISSUE THREAD

**Issue by girishso** [elm-lang/projects#17]
I just got elm repl working in browser.  Check out at http://elmrepl.cuberoot.in

Feedback most welcome! :)

**Comment by evancz** [comment]
This is really cool! Can you share on [elm-dev](https://groups.google.com/forum/#!forum/elm-dev) about this?

I think it may be worth pointing folk to this so they can use it as they go through [this section of the guide](https://guide.elm-lang.org/core_language.html) if they don't want to install. I'd want some folks to test that though to see if it all goes smoothly, so hopefully elm-dev people can help with that.

Visually, I'd just say no more cursive font in the header. Use a sans-serif font, ideally the same ones as on the elm-lang.org website. And it'd be cool if the color scheme matched http://elm-lang.org/try

**Comment by girishso** [comment]
@evancz made the visual changes suggested by you.  Just wanted to say thank you for creating Elm! :)

**Comment by girishso** [comment]
whoops!  I styled as per the elm site and not elm try :(

**Comment by evancz** [comment]
Still looking good! I'll make a thread on elm-dev about this. Is the code open source?

Also, thanks, glad you are liking it!

**Comment by evancz** [comment]
Alright, here is [the thread](https://groups.google.com/forum/#!topic/elm-dev/RfxkV-p7ApA)!

**Comment by girishso** [comment]
Thanks for posting on Elm dev, it's difficult to find time when my kid is around!

I will open the frontend code, will like to keep the server side closed for the time being at-least.

**Comment by evancz** [comment]
Sounds good, and sorry some folks gave you a hard time! It's always kind of discouraging when you do something cool and everyone is like "what about all this other stuff that is unrelated or out of scope?!"

I'll try to do some hand testing of guide stuff myself and add a link if I can work through everything. In any case, this is really cool! :D

**Comment by girishso** [comment]
:)

Thanks for the encouraging words!

IMO there is no need of any testing, it's just the elm-repl shell shared in browser, except backslash does not work.

Btw. I tried adding link to this in https://guide.elm-lang.org/core_language.html, but it's a gitbook and found no way of forking and creating a PR.

**Comment by girishso** [comment]
@evancz realized only now that the repl is linked from the official docs!

Thank you! :)

**Comment by evancz** [comment]
Oh, I guess I forgot to ping you when I added the link. Sorry about that! D:

But yeah! It's been up for quite a while now, and it seems to be working well for folks. Great work! And thanks for creating it!
