### ISSUE TITLE
Who is working on what?

### ISSUE THREAD

**Issue by pdavidow** [elm-lang/projects#18]
I am thinking of working on one of these projects (perhaps Visualize Compilation), but maybe someone else is already doing so. 
How does one find out who -- if anybody -- is working on what in this list?

**Comment by evancz** [comment]
I'd ask around on elm-discuss, but I think it's better that you don't block on anyone else who claims they are working on it.

It's easy to say you are doing something, but no one should block on that. Sometimes people just say things! And if a bunch of folks have fun giving it a shot, it's no big deal. That means a bunch of folks got to work on a cool project. And if someone has actually done it well in a releasable way, it will come off this list.
