### ISSUE TITLE
Is a markdown parser written entirely in Elm still needed?

### ISSUE THREAD

**Issue by squaresurf** [elm-lang/projects#23]
I am interested in working on this project, but recently came across this: [pablohirafuji/elm-markdown](http://package.elm-lang.org/packages/pablohirafuji/elm-markdown/latest). Is the desire for an elm only markdown parser satisfied by that or do we want closer parity with [evancz/elm-markdown](http://package.elm-lang.org/packages/evancz/elm-markdown/latest)?

@pablohirafuji may also have a different plan for his project :smile:

**Comment by pablohirafuji** [comment]
Hi, `pablohirafuji/elm-markdown` were coded using regex. Evan added this project after the release of my package. Based on the description, I think a markdown parser using `elm-tools/parser` or something more specific, without using regex, would be more appropriate. I tried to code it using `elm-tools/parser` after some time, but the performance for just parsing the block parts was > 10x slower than using regex.

I am really busy right now, so feel free to tackle this. I think @BrianHicks was coding this.

**Comment by squaresurf** [comment]
Ah, that makes sense. Thank you for the insight @pablohirafuji.

@BrianHicks is this something you're actively working on?

**Comment by BrianHicks** [comment]
It was a part of a yak shave on a personal project but I found another way around. Plus I had the same question you did, @squaresurf. If you’re gonna give it a try, the commonmark spec is really nice and has a good parsing strategy in one of the appendices.

So same as @pablohirafuji: I have too much going on right now to say I’d ship anything anytime soon.

**Comment by squaresurf** [comment]
Sounds good. Thank you for letting me know. When I get a bit of time I'll dive in. I'm thinking I may wait to announce/share the lib until it's 1.0 (i.e. full parity with `evancz/elm-markdown`). Does that match the general pattern for the community?

I will definitely give commonmark a look as well as write tests to ensure that it follows the spec. I'd also like to have tests for GitHub Flavored Markdown since `evancz/markdown` supports that as well.

I'm also planning on writing a benchmark runner so I can keep an eye on the speed compared to the two `elm-markdown` libs. I can also compare with the other js libs that `pablohirafuji/elm-markdown` compares to with regards to benchmarks.

Any suggestions on a name? `elm-markdown` is already used twice.

**Comment by BrianHicks** [comment]
IMO a smaller target would be better. This is a big project, and there’s no reason to make the scope even bigger. If it will help, please go ahead and steal/borrow whatever code you need from BrianHicks/elm-commonmark. It’s BSD3 but I’m giving you special permission not to credit me if it’ll help you get something out the door.

As far as a name: this is why Elm libraries are namespaced. If you go with commonmark, call it that. If it’s GFM, call it that. Be direct.

**Comment by squaresurf** [comment]
That is great advice. I will shoot for a smaller target (i.e. commonmark). That being said, I would like it to eventually support GFM as well as a few other of my current use cases. Composition of smaller markdown libraries would make it possible to have those in separate libraries as well, so maybe that is a better approach.

Thank you for the permission to not credit you. At a minimum, unless you prefer me not to, I will add your name in a thank you section. I will also read the license to see if I can follow it and still pick my own open source license. I'm more familiar with the MIT license, but I may go with BSD3 as well this time around.

Is that repo, a good example of the general layout of an elm lib? If not, do you have a few shining examples of how to organize the files? This will be my first public elm lib. I like that it has a Makefile rather than a package.json :smile:.

**Comment by BrianHicks** [comment]
It’s how I like to do it. That said, my libraries are fairly idiosyncratic. Works for me, might not be great for others (especially those folks unfamiliar with make.)

That said, this is probably a question better suited for Discourse or Slack, and we seem to have resolved your original question, so can we consider this issue resolved?

**Comment by squaresurf** [comment]
Yes, I'm sorry for going on longer than I should. If I have more questions, then I'll post on slack or disclosure :smile:.

**Comment by BrianHicks** [comment]
Nah, you’re fine. It’s just that you’ll get better answers in those places because there are more people. 😄

**Comment by squaresurf** [comment]
I've been quite excited about this project, but have learned the hard way that I really don't have the time needed to push this forward. I'm posting this here so that future visitors to this Issue will know to pick this up if they'd like. I'll post a comment here if I'm able to start working on this again in the future.
