### ISSUE TITLE
Is process bot still used?

### ISSUE THREAD

**Issue by razzeee** [elm-lang/projects#25]
Should we remove the section about process bot? The bot doesn't seem to do anything anymore.

**Comment by evancz** [comment]
It was running on a server that was turned off with the switch to 0.19, so I am working on getting a server going to do a couple little tasks. It will come back in time!

**Comment by razzeee** [comment]
Sorry, that confuses me even more, according to https://github.com/process-bot it was last active in summer of 2016. Is that the wrong bot or is the account setup to hide comments? Maybe you just ment to write 0.18?

**Comment by evancz** [comment]
The code doesn't need to be changed to run on a server, and I don't think you get marks for commenting on issues.
