### ISSUE TITLE
Please update roadmap.md

### ISSUE THREAD

**Issue by bbkane** [elm-lang/projects#26]
Hello - I got to the roadmap from [ports guide page](https://guide.elm-lang.org/interop/ports.html), and, while I'm very new to Elm, I don't think it's been updated for 0.19. 

For example, here's some verbage (emphasis mine):

---

Like this, and 0.19 *will* improve asset management.

The major focus of 0.19 *will be* creating “single-page apps” in Elm. The features that fall under that umbrella include:

---

I'd appreciate it if someone updated this to account for the fact that Elm is 0.19 now, and hopefully adjust the goals as well.
Thank you!

**Comment by bbkane** [comment]
Maybe `elm-make` in README.md should be replaced with `elm make`, too. I'm sorry, but I'm too new to catch any less obvious upgrades to account for the 0.18 -> 0.19 transition.

**Comment by heyakyra** [comment]
Seems like this is something for @evancz who is probably pretty busy

**Comment by eloraiby** [comment]
@evancz any update for the roadmap to 0.20 ? What is important is to know what kind of features are going to be deprecated, and what is going to stay. Seriously considering Elm for a new project, but affraid that there are going to be some breaking changes like what happened from 0.18 to 0.19. Hope you answer ASAP.

**Comment by bbkane** [comment]
From Slack ( https://elmlang.slack.com/archives/C13L7S5GR/p1578996784006300 ):

warry Jan 14th at 02:13
@evancz what are the current themes/orientation for the ecosystem ? usualy after a release you give some informations about your intents for the next release, it doesn't seems to be the case for 0.19.1 (unless I'm mistaken). are you ready to share some of the directions you'd like to take ?
:100:
12

9 replies

sashaafm  15 days ago
I concur I also feel the need for this. Specially about the WebSocket API
:+1:
8


evancz  15 days ago
I am trying to plan out some larger projects. Possible directions include:
- Elm for researchers (data visualization, file formats, etc.)
- Elm for learning programming (middle school and high school)
- Improving testing
- Revisiting routing, asset sizes, etc.
I have been doing exploratory work in all of these areas. The goal is to do something that grows the community in a healthy way (new types of users) or that does something more technically interesting than the last two releases. The particular path will depend on what happens in this exploratory phase.
:+1:
23
:clap:
7
:school:
6


cjmeeks  15 days ago
Any plan for web apis? Such as websockets from the comment above?

evancz  15 days ago
I recommend using ports for websockets.
The old API couldn't cover everything that was needed due to the underlying design of "effect modules" which is somewhat odd. I do not think a library can cover all websockets features in a nice way with the current design of effect modules.
So if advanced users will need to use ports eventually, I don't think it is so good to point them to a library that they will outgrow. Obviously not everyone agrees with me on this.

Julian Antonielli  15 days ago
Do you plan to revisit the design of effect managers eventually to cover more use cases/web apis?

evancz  15 days ago
I have thought a lot about the design of effect managers, and it doesn't feel particularly promising. Even if it was promising, the context is:
1. HTTP is trying to subsume WebSockets
2. A lot of people want to use WebSockets for things like Elixir or Meteor where they have some library to do that in JS with lots of particular details that probably won't be exactly replicable with whatever design is possible.
It feels like there are more promising things for the community overall, and the folks who could benefit from working on this and the work actually panning out (which again, I don't really think is what would happen) are not actually blocked in a major way.
So I am planning to focus on the four general categories outlined above. I think that'll be better overall. (edited) 
:-1:
1
:+1:
7

**Comment by dullbananas** [comment]
2 and a half years layer and this still isn't updated @evancz

**Comment by bbkane** [comment]
An update on Discourse: https://discourse.elm-lang.org/t/where-can-we-find-the-roadmap-of-elm/6038 .
Rough Summary:
- Elm is going to be stable for a while
- Evan is working on some unnamed exploratory stuff
- "If someone needs more certainty, I generally recommend looking into other languages to see if they have a balance that works better for their needs. For example, languages made by big corporations are generally “less risky” on things like this, but I think you see the fruits of that kind of process in the design decisions as well. Trade offs!"

**Comment by dullbananas** [comment]
close this @evancz
