### ISSUE TITLE
Markdown parser

### ISSUE THREAD

**Issue by razzeee** [elm-lang/projects#28]
There seems to be https://package.elm-lang.org/packages/pablohirafuji/elm-markdown/latest/ that's a markdown parser completly written in elm.

So https://github.com/elm/projects#markdown-parser might be outdated?

**Comment by rlefevre** [comment]
https://package.elm-lang.org/packages/pablohirafuji/elm-markdown/latest/ is using regexs though, so maybe a pure parser using elm/parser would still be a nice addition: see https://github.com/elm/projects/issues/23

**Comment by evancz** [comment]
Okay, looks like it makes sense to keep it up! Thanks for the extra info @rlefevre!
