### ISSUE TITLE
Version string in elm-package documentation

### ISSUE THREAD

**Issue by jastice** [elm-lang/projects#4]
It would be helpful to provide a ready-made safe version string for inclusion in `elm-package.json` in the elm package documentation pages. For example the [core library v1.1.0](http://package.elm-lang.org/packages/elm-lang/core/1.1.0) would show somewhere:

> To use in your project, add to your elm-package.json: `"elm-lang/core": "1.1.0 <= v < 2.0.0"`

I can probably do this sometime, leaving this here as a reminder and for comments :)

**Comment by squaresurf** [comment]
Is this still needed?

**Comment by jastice** [comment]
I don't know, haven't actively used Elm for a while :)

**Comment by squaresurf** [comment]
When looking at http://package.elm-lang.org/packages/elm-lang/core/5.1.1 I don't see a version string to add to your `elm-package.json`.  Is that the sort of feature you were wanting @jastice?

@evancz would you like this sort of feature in this repo's list or should this be moved to another repo? I think it would be a good thing to not have a stale issue hanging out on a repo like this. :smile:

p.s. I'm sorry if I should not have mentioned @evancz. Feel free to mention/assign to the appropriate person.

**Comment by jastice** [comment]
Yes, that is what I had in mind.

**Comment by evancz** [comment]
I want to keep the projects as relatively self-contained: not needing coordination with core people, possible to work on independently for a long time, etc. I don't think this matches that criteria.
