### ISSUE TITLE
convert html to elm

### ISSUE THREAD

**Issue by flip111** [elm-lang/projects#9]
Would be nice to have a package that does a best effort to convert static html to elm. This can help when you want to port an existing website.

**Comment by evancz** [comment]
Search elm-discuss, @avh4 made an experimental thing that can do this.

**Comment by avh4** [comment]
Online tool to convert html to elm: http://elm-compile-html.herokuapp.com/

npm module for a command line tool to do the same conversion: https://github.com/avh4/elm-compile-html

**Comment by evancz** [comment]
Cool, I did not know about the online tool, that's really great! :D
